# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: waypoint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'waypoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewaypoint.proto\x12\x08sidewalk\"5\n\x0cWaypointTile\x12%\n\twaypoints\x18\x01 \x03(\x0b\x32\x12.sidewalk.Waypoint\"\xae\x02\n\x08Waypoint\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08latitude\x18\x03 \x01(\x01\x12\x11\n\tlongitude\x18\x04 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\x12\x11\n\tembedding\x18\x08 \x03(\x02\x12\x1a\n\x12\x65mbedding_document\x18\t \x01(\t\x12\r\n\x05types\x18\x0b \x01(\t\x12\x1a\n\x12visual_description\x18\x0e \x01(\t\x12\x18\n\x10visual_embedding\x18\x0f \x03(\x02\x12\r\n\x05phone\x18\x11 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x12 \x01(\t\x12\x15\n\rmapillary_ids\x18\x16 \x03(\t\x12\x0f\n\x07website\x18\x17 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'waypoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAYPOINTTILE']._serialized_start=28
  _globals['_WAYPOINTTILE']._serialized_end=81
  _globals['_WAYPOINT']._serialized_start=84
  _globals['_WAYPOINT']._serialized_end=386
# @@protoc_insertion_point(module_scope)
